### ISSUE TITLE
[request] installation instructions

### ISSUE THREAD

**Issue by FranzSkuffka** [rupa/v#13]
installation guides would be awesome+ for nubs like me.

thank you.

**Comment by siddharthist** [comment]
I'd also like to see this. I could probably figure it out, but it's an immediate barrier to entry.

**Comment by shmup** [comment]
Well for now I can tell you that you should put `v` somewhere in your path.

In console do `echo $PATH` and ideally you'll maybe see your home bin directory: `~/bin`

If not, Google how to do that and you should be good to go (once you've put `v` in there).
